services:
  lldap:
    image: lldap/lldap:${LLDAP_VERSION}
    restart: unless-stopped
    ports:
      - "17170:17170"
    environment:
      UID: 1000
      GID: 1000
      TZ: America/New_York
      LLDAP_JWT_SECRET_FILE: /secrets/JWT_SECRET
      LLDAP_KEY_SEED_FILE: /secrets/KEY_SEED
      LLDAP_LDAP_USER_PASS_FILE: /secrets/LDAP_USER_PASS
      LLDAP_LDAP_BASE_DN: dc=fernandoarteaga,dc=dev
      LLDAP_LDAP_USER_DN: admin # default admin user
      LLDAP_LDAP_USER_EMAIL: me@fernandoarteaga.dev # default admin email
      #LLDAP_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PWD}@${POSTGRES_HOST}/${LLDAP_DB_NAME}
    volumes:
      - ./lldap/secrets:/secrets
      - lldap:/data
    networks:
      - ${DOCKER_NETWORK}

  authelia:
    image: authelia/authelia:${AUTHELIA_VERSION}
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    environment:
      TZ: America/New_York
      X_AUTHELIA_CONFIG_FILTERS: expand-env,template
      #AUTHELIA_NOTIFIER_SMTP_ADDRESS: submission://smtp.sendgrid.net:587
      #AUTHELIA_NOTIFIER_SMTP_USERNAME: apikey                       # replace with your SMTP server's username
      #AUTHELIA_NOTIFIER_SMTP_SENDER: "Your Name <name@domain.com>"  # replace with your name/email
      #AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /secrets/NOTIFIER_SMTP_PASSWORD
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_ADDRESS: ldap://lldap:3890
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_BASE_DN: dc=fernandoarteaga,dc=dev  # must be identical to what is configured in lldap
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_USER=uid: admin,ou=people,dc=fernandoarteaga,dc=dev # must be the DN of your admin configured in lldap
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /secrets/STORAGE_ENCRYPTION_KEY
      AUTHELIA_STORAGE_LOCAL_PATH: /storage/db.sqlite3
      #AUTHELIA_STORAGE_POSTGRES_ADDRESS: tcp://${POSTGRES_HOST}:${POSTGRES_PORT}
      #AUTHELIA_STORAGE_POSTGRES_USERNAME: ${POSTGRES_USER}
      #AUTHELIA_STORAGE_POSTGRES_PASSWORD: ${POSTGRES_PWD}
      #AUTHELIA_STORAGE_POSTGRES_DATABASE: ${AUTHELIA_DB_NAME}
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE: /secrets/OIDC_HMAC_SECRET
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: /secrets/JWT_SECRET
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE: /secrets/AUTHENTICATION_BACKEND_LDAP_PASSWORD
      #AUTHELIA_SESSION_SECRET_FILE: /secrets/SESSION_SECRET # Redis
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.entrypoints=https'
      - 'traefik.http.routers.authelia.rule=Host(`auth.fernandoarteaga.dev`)'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/verify?rd=https://auth.fernandoarteaga.dev'
      - 'traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
    volumes:
      - authelia:/storage
      - ./authelia/config:/config
      - ./authelia/secrets:/secrets
    networks:
      - ${DOCKER_NETWORK}

networks:
  homelab:
    external: true
volumes:
  lldap:
  authelia:
